name: CI

on:
  pull_request_target:
    types: [ opened, synchronize ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          PR_HEAD_REF=${{ github.event.pull_request.head.ref }}
          echo "$PR_HEAD_REF"
